-- Supabase SQL Migration: Multi-User Auth, RLS, and Expenses Table

-- 1. Add user_id to existing tables (with default to the current authenticated user)
-- Note: Assuming you're migrating an existing DB. If the tables are empty, this is fine. 
-- If they have data and you want to assign them to a specific user first, you may need to handle that.
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid();
-- It's best practice to make it NOT NULL after assigning, but we'll leave it as DEFAULT auth.uid() for now.

-- 2. Create the expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  expense_type TEXT NOT NULL,
  price REAL NOT NULL,
  date TEXT NOT NULL,
  notes TEXT
);

-- 2b. Add repeating notification columns to reminders table
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS repeat_interval_days INTEGER;
ALTER TABLE reminders ADD COLUMN IF NOT EXISTS active_notification_ids TEXT;

-- 3. Enable Row Level Security (RLS) on all tables
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE refueling_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE accessories ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_intervals ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for the authenticated user

-- Vehicles Policy
CREATE POLICY "Users can manage their own vehicles" 
ON vehicles FOR ALL USING (auth.uid() = user_id);

-- Because the other tables are linked to vehicles, you could technically create policies 
-- that join the vehicles table to check the user_id. 
-- But for simplicity and performance in Supabase, we can add user_id to them as well,
-- or use a subquery in the policy. Here we use a subquery.

-- Refueling Events Policy
CREATE POLICY "Users can manage refueling events for their vehicles"
ON refueling_events FOR ALL 
USING (vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid()));

-- Maintenance Events Policy
CREATE POLICY "Users can manage maintenance for their vehicles"
ON maintenance_events FOR ALL 
USING (vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid()));

-- Service Items Policy
CREATE POLICY "Users can manage service items for their vehicles"
ON service_items FOR ALL 
USING (maintenance_event_id IN (SELECT id FROM maintenance_events WHERE vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid())));

-- Accessories Policy
CREATE POLICY "Users can manage accessories for their vehicles"
ON accessories FOR ALL 
USING (vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid()));

-- Expenses Policy
CREATE POLICY "Users can manage expenses for their vehicles"
ON expenses FOR ALL 
USING (vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid()));

-- Service Intervals Policy
CREATE POLICY "Users can manage service intervals for their vehicles"
ON service_intervals FOR ALL 
USING (vehicle_id IN (SELECT id FROM vehicles WHERE user_id = auth.uid()));
